[package]
name = "anole-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "Command-line interface for Anole"

[[bin]]
name = "anole"
path = "src/main.rs"

[dependencies]
clap.workspace = true
anole-core = { version = "=0.1.1", path = "../core" }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true

[lints]
workspace = true
