#requires -Version 7.0
# Generates windows-explorer-hooks.nsh and register_dev_explorer_convert.ps1
# from apps/desktop/src-tauri/explorer-verbs.json. Do not hand-edit those outputs.

[CmdletBinding()]
param(
    [string]$Table = (Join-Path $PSScriptRoot '..\apps\desktop\src-tauri\explorer-verbs.json'),
    [string]$Nsh = (Join-Path $PSScriptRoot '..\apps\desktop\src-tauri\windows-explorer-hooks.nsh'),
    [string]$RegisterScript = (Join-Path $PSScriptRoot 'register_dev_explorer_convert.ps1'),
    [switch]$Check
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$tablePath = (Resolve-Path -LiteralPath $Table).Path
$spec = Get-Content -LiteralPath $tablePath -Raw -Encoding utf8 | ConvertFrom-Json
if ($spec.convert.Count -ne 25) {
    throw "explorer-verbs.json must declare exactly 25 convert verbs, found $($spec.convert.Count)"
}

function New-Nsh {
    $lines = @(
        '!macro FW_CONVERT_VERB ASSOC VERB TARGET LABEL',
        '  WriteRegStr SHCTX "Software\Classes\SystemFileAssociations\${ASSOC}\shell\${VERB}" "MUIVerb" "${LABEL}"',
        '  WriteRegStr SHCTX "Software\Classes\SystemFileAssociations\${ASSOC}\shell\${VERB}" "Icon" "$INSTDIR\${MAINBINARYNAME}.exe,0"',
        '  WriteRegStr SHCTX "Software\Classes\SystemFileAssociations\${ASSOC}\shell\${VERB}\command" "" ''"$INSTDIR\${MAINBINARYNAME}.exe" --shell-convert --to ${TARGET} "%1"''',
        '!macroend',
        '',
        '!macro FW_DELETE_CONVERT_VERB ASSOC VERB',
        '  DeleteRegKey SHCTX "Software\Classes\SystemFileAssociations\${ASSOC}\shell\${VERB}"',
        '!macroend',
        '',
        '!macro FW_DIRECTORY_CONVERT_VERB VERB TARGET LABEL',
        '  WriteRegStr SHCTX "Software\Classes\Directory\shell\${VERB}" "MUIVerb" "${LABEL}"',
        '  WriteRegStr SHCTX "Software\Classes\Directory\shell\${VERB}" "Icon" "$INSTDIR\${MAINBINARYNAME}.exe,0"',
        '  WriteRegStr SHCTX "Software\Classes\Directory\shell\${VERB}\command" "" ''"$INSTDIR\${MAINBINARYNAME}.exe" --shell-convert --to ${TARGET} "%1"''',
        '!macroend',
        '',
        '!macro FW_DELETE_DIRECTORY_CONVERT_VERB VERB',
        '  DeleteRegKey SHCTX "Software\Classes\Directory\shell\${VERB}"',
        '!macroend',
        '',
        '!macro NSIS_HOOK_POSTINSTALL',
        '  WriteRegStr SHCTX "Software\Classes\*\shell\Anole" "MUIVerb" "Open in Anole"',
        '  WriteRegStr SHCTX "Software\Classes\*\shell\Anole" "Icon" "$INSTDIR\${MAINBINARYNAME}.exe,0"',
        '  WriteRegStr SHCTX "Software\Classes\*\shell\Anole\command" "" ''"$INSTDIR\${MAINBINARYNAME}.exe" --shell-open "%1"''',
        '',
        '  WriteRegStr SHCTX "Software\Classes\Directory\shell\Anole" "MUIVerb" "Open in Anole"',
        '  WriteRegStr SHCTX "Software\Classes\Directory\shell\Anole" "Icon" "$INSTDIR\${MAINBINARYNAME}.exe,0"',
        '  WriteRegStr SHCTX "Software\Classes\Directory\shell\Anole\command" "" ''"$INSTDIR\${MAINBINARYNAME}.exe" --shell-open "%1"''',
        ''
    )
    # E-06: convert verbs are registered at runtime by the application
    # (HKCU, settings-editable); the installer only bootstraps them once and
    # the uninstall hooks below stay as the cleanup backstop.
    $lines += @(
        '  ExecWait ''"$INSTDIR\${MAINBINARYNAME}.exe" --register-shell''',
        '!macroend',
        '',
        '!macro NSIS_HOOK_PREUNINSTALL',
        '  DeleteRegKey SHCTX "Software\Classes\*\shell\Anole"',
        '  DeleteRegKey SHCTX "Software\Classes\Directory\shell\Anole"'
    )
    foreach ($item in $spec.convert) {
        if ($item.assoc -eq 'Directory') {
            $lines += "  !insertmacro FW_DELETE_DIRECTORY_CONVERT_VERB `"$($item.verb)`""
        } else {
            $lines += "  !insertmacro FW_DELETE_CONVERT_VERB `"$($item.assoc)`" `"$($item.verb)`""
        }
    }
    $lines += '!macroend'
    $lines += ''
    return ($lines -join "`n")
}

function New-RegisterScript {
    $verbLines = foreach ($item in $spec.convert) {
        "    @{ Assoc = '$($item.assoc)'; Verb = '$($item.verb)'; Target = '$($item.target)'; Label = '$($item.label)' },"
    }
    $verbBlock = ($verbLines -join "`n").TrimEnd(',')
    return @"
# Generated by scripts/generate_explorer_verbs.ps1 from explorer-verbs.json.
# Registers current-user Explorer convert verbs for a local desktop exe.
param(
    [string]`$Executable = (Join-Path `$PSScriptRoot '..\target\release\anole-desktop.exe'),
    [switch]`$Remove
)

`$ErrorActionPreference = 'Stop'
`$exe = [System.IO.Path]::GetFullPath(`$Executable)
`$verbs = @(
$verbBlock
)

foreach (`$item in `$verbs) {
    `$shellRoot = if (`$item.Assoc -eq 'Directory') { "Registry::HKEY_CURRENT_USER\Software\Classes\Directory\shell" } else { "Registry::HKEY_CURRENT_USER\Software\Classes\SystemFileAssociations\`$(`$item.Assoc)\shell" }
    `$key = Join-Path `$shellRoot `$item.Verb
    if (`$Remove) {
        if (Test-Path -LiteralPath `$key) {
            Remove-Item -LiteralPath `$key -Recurse -Force
        }
        continue
    }
    if (-not (Test-Path -LiteralPath `$exe)) {
        throw "desktop executable not found: `$exe"
    }
    New-Item -Path `$key -Force | Out-Null
    New-ItemProperty -LiteralPath `$key -Name 'MUIVerb' -Value `$item.Label -Force | Out-Null
    New-ItemProperty -LiteralPath `$key -Name 'Icon' -Value "`$exe,0" -Force | Out-Null
    `$commandKey = Join-Path `$key 'command'
    New-Item -Path `$commandKey -Force | Out-Null
    Set-ItemProperty -LiteralPath `$commandKey -Name '(default)' -Value ('"' + `$exe + '" --shell-convert --to ' + `$item.Target + ' "%1"')
}

if (`$Remove) {
    Write-Host 'Removed current-user Anole convert verbs.'
} else {
    Write-Host "Registered convert verbs for `$exe"
    Write-Host 'Classic Explorer: right-click a PDF and choose Convert to PNG (Windows 11: Show more options).'
}
"@
}

function Normalize-Text([string]$Text) {
    return ($Text -replace "`r`n", "`n").TrimEnd() + "`n"
}

$nshText = Normalize-Text (New-Nsh)
$ps1Text = Normalize-Text (New-RegisterScript)

if ($Check) {
    $existingNsh = Normalize-Text (Get-Content -LiteralPath $Nsh -Raw -Encoding utf8)
    $existingPs1 = Normalize-Text (Get-Content -LiteralPath $RegisterScript -Raw -Encoding utf8)
    if ($existingNsh -cne $nshText -or $existingPs1 -cne $ps1Text) {
        throw 'generated explorer verb files are stale; run scripts/generate_explorer_verbs.ps1'
    }
    Write-Host 'explorer verb generated files match explorer-verbs.json'
    return
}

Set-Content -LiteralPath $Nsh -Value $nshText -Encoding utf8NoBOM -NoNewline
Set-Content -LiteralPath $RegisterScript -Value $ps1Text -Encoding utf8NoBOM -NoNewline
Write-Host "Wrote $Nsh"
Write-Host "Wrote $RegisterScript"
