# Generated by scripts/generate_explorer_verbs.ps1 from explorer-verbs.json.
# Registers current-user Explorer convert verbs for a local desktop exe.
param(
    [string]$Executable = (Join-Path $PSScriptRoot '..\target\release\anole-desktop.exe'),
    [switch]$Remove
)

$ErrorActionPreference = 'Stop'
$exe = [System.IO.Path]::GetFullPath($Executable)
$verbs = @(
    @{ Assoc = '.pdf'; Verb = 'Anole.ToPng'; Target = 'png'; Label = 'Convert to PNG' },
    @{ Assoc = '.pdf'; Verb = 'Anole.ToJpg'; Target = 'jpg'; Label = 'Convert to JPG' },
    @{ Assoc = '.png'; Verb = 'Anole.ToWebp'; Target = 'webp'; Label = 'Convert to WebP' },
    @{ Assoc = '.jpg'; Verb = 'Anole.ToWebp'; Target = 'webp'; Label = 'Convert to WebP' },
    @{ Assoc = '.jpeg'; Verb = 'Anole.ToWebp'; Target = 'webp'; Label = 'Convert to WebP' },
    @{ Assoc = '.json'; Verb = 'Anole.ToYaml'; Target = 'yaml'; Label = 'Convert to YAML' },
    @{ Assoc = '.csv'; Verb = 'Anole.ToJson'; Target = 'json'; Label = 'Convert to JSON' },
    @{ Assoc = '.yaml'; Verb = 'Anole.ToJson'; Target = 'json'; Label = 'Convert to JSON' },
    @{ Assoc = '.yml'; Verb = 'Anole.ToJson'; Target = 'json'; Label = 'Convert to JSON' },
    @{ Assoc = '.xml'; Verb = 'Anole.ToJson'; Target = 'json'; Label = 'Convert to JSON' },
    @{ Assoc = '.mp4'; Verb = 'Anole.ToMp3'; Target = 'mp3'; Label = 'Convert to MP3' },
    @{ Assoc = '.mkv'; Verb = 'Anole.ToMp4'; Target = 'mp4'; Label = 'Convert to MP4' },
    @{ Assoc = '.mov'; Verb = 'Anole.ToMp4'; Target = 'mp4'; Label = 'Convert to MP4' },
    @{ Assoc = '.avi'; Verb = 'Anole.ToMp4'; Target = 'mp4'; Label = 'Convert to MP4' },
    @{ Assoc = '.webm'; Verb = 'Anole.ToMp4'; Target = 'mp4'; Label = 'Convert to MP4' },
    @{ Assoc = '.mp3'; Verb = 'Anole.ToWav'; Target = 'wav'; Label = 'Convert to WAV' },
    @{ Assoc = '.wav'; Verb = 'Anole.ToMp3'; Target = 'mp3'; Label = 'Convert to MP3' },
    @{ Assoc = 'Directory'; Verb = 'Anole.FolderToJpg'; Target = 'jpg'; Label = 'Convert folder to JPG' },
    @{ Assoc = 'Directory'; Verb = 'Anole.FolderToWebp'; Target = 'webp'; Label = 'Convert folder to WebP' }
)

foreach ($item in $verbs) {
    $shellRoot = if ($item.Assoc -eq 'Directory') { "Registry::HKEY_CURRENT_USER\Software\Classes\Directory\shell" } else { "Registry::HKEY_CURRENT_USER\Software\Classes\SystemFileAssociations\$($item.Assoc)\shell" }
    $key = Join-Path $shellRoot $item.Verb
    if ($Remove) {
        if (Test-Path -LiteralPath $key) {
            Remove-Item -LiteralPath $key -Recurse -Force
        }
        continue
    }
    if (-not (Test-Path -LiteralPath $exe)) {
        throw "desktop executable not found: $exe"
    }
    New-Item -Path $key -Force | Out-Null
    New-ItemProperty -LiteralPath $key -Name 'MUIVerb' -Value $item.Label -Force | Out-Null
    New-ItemProperty -LiteralPath $key -Name 'Icon' -Value "$exe,0" -Force | Out-Null
    $commandKey = Join-Path $key 'command'
    New-Item -Path $commandKey -Force | Out-Null
    Set-ItemProperty -LiteralPath $commandKey -Name '(default)' -Value ('"' + $exe + '" --shell-convert --to ' + $item.Target + ' "%1"')
}

if ($Remove) {
    Write-Host 'Removed current-user Anole convert verbs.'
} else {
    Write-Host "Registered convert verbs for $exe"
    Write-Host 'Classic Explorer: right-click a PDF and choose Convert to PNG (Windows 11: Show more options).'
}
